--- !ruby/object:Jumpstart::Configuration
application_name: MakerFlow
business_name: CreativeApps SASU
domain: example.com
support_email: hello@creativeapps.studio
default_from_email: Jumpstart <support@example.com>
business_address: 66, Avenue des Champs-Elysées
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: false
solargraph: false
register_with_account: false
